source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BSDatePicker_Example', :exclusive => true do
  pod 'BSDatePicker', :path => '../'
end

target 'BSDatePicker_Tests', :exclusive => true do
  pod 'BSDatePicker', :path => '../'

  
end
